version: 2

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: "05:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 99
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: "05:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 5
