# Security: 7-day delay before using newly published packages (10,080 minutes)
minimumReleaseAge: 10080
# Exclude Airtasker packages from release age delay
minimumReleaseAgeExclude:
  - "@airtasker/*"
