name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      node-versions: ${{ steps.set.outputs.node-versions }}
      latest-node: ${{ steps.set.outputs.latest-node }}
    steps:
      - id: set
        run: |
          NODE_VERSIONS='["18","20","22","24"]'
          echo "node-versions=${NODE_VERSIONS}" >> $GITHUB_OUTPUT
          echo "latest-node=$(echo "${NODE_VERSIONS}" | jq -r 'last')" >> $GITHUB_OUTPUT

  build:
    name: "build-node-${{ matrix.node-version }}"
    runs-on: ubuntu-latest
    needs: config
    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJson(needs.config.outputs.node-versions) }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm build
      - uses: actions/cache/save@v5
        with:
          key: build-${{ github.sha }}-${{ matrix.node-version }}
          path: dist/

  test:
    name: "test-node-${{ matrix.node-version }}"
    runs-on: ubuntu-latest
    needs: [config, build]
    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJson(needs.config.outputs.node-versions) }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests
        env:
          JEST_JUNIT_OUTPUT_DIR: ./test-reports/jest
          JEST_JUNIT_OUTPUT_NAME: results.xml
          JEST_JUNIT_CLASSNAME: "{filepath}"
        run: pnpm ci:test
      - uses: actions/upload-artifact@v7
        with:
          name: test-results-node-${{ matrix.node-version }}
          path: ./test-reports
      - uses: test-summary/action@v2
        with:
          paths: ./test-reports/jest/results.xml

  lint:
    name: "lint-node-${{ matrix.node-version }}"
    runs-on: ubuntu-latest
    needs: config
    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJson(needs.config.outputs.node-versions) }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm lint:check

  integration-test:
    name: "integration-test-node-${{ matrix.node-version }}"
    runs-on: ubuntu-latest
    needs: [config, build]
    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJson(needs.config.outputs.node-versions) }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache/restore@v5
        with:
          key: build-${{ github.sha }}-${{ matrix.node-version }}
          path: dist/
      - run: npm link
      - run: npx proxay --help
      - run: |
          npx proxay -m record -h https://www.google.com -t tapes/ &
          # Wait until it loads.
          until (curl http://localhost:3000 2>&1 | grep Google &>/dev/null)
          do
            echo "Waiting until server ready..."
            sleep 5
          done

  all-tests-pass:
    runs-on: ubuntu-latest
    needs: [test, lint, build, integration-test]
    if: always()
    steps:
      - name: Check all jobs passed
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            exit 1
          fi

  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: [config, test, build, lint, integration-test]
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ needs.config.outputs.latest-node }}
          registry-url: "https://registry.npmjs.org"
      - uses: actions/cache/restore@v5
        with:
          key: build-${{ github.sha }}-${{ needs.config.outputs.latest-node }}
          path: dist/
      - name: Publish to npm registry
        run: npm publish --provenance --access public
